### PR TITLE
feat: kinde auth for convex

### PR DESCRIPTION
**Pull request by umuthopeyildirim**
This pull request introduces support for Kinde Auth in the Convex application. A significant portion of the implementation was adapted from the existing 0Auth integration, with adjustments made to accommodate Kinde Auth's specifications. Special thanks to @xixixao for their foundational work on authentication which this PR builds upon.

While the changes compile successfully, I have encountered issues with testing the integration locally. I am reaching out to the team for assistance with local deployment and testing procedures to ensure this feature's functionality. 

I would greatly appreciate feedback on the current code, particularly concerning any outdated practices that may have been carried over from the 0Auth codebase. If there are existing tutorials or documentation on setting up a local development environment for Convex, sharing these resources would be extremely helpful.

Additionally, here's an example of how Kinde Auth has been implemented in a similar React project for reference: [react-kinde-convex](https://github.com/umuthopeyildirim/react-kinde-convex).

### CODE REVIEW

**Comment by xixixao** [comment]
Hey @umuthopeyildirim, thanks for the great contribution! We're reviewing it internally, and might decide to keep this integration in a separate NPM package (eventually all auth integrations might go into separate packages). Will keep you posted here on what we decide.

**Comment by umuthopeyildirim** [comment]
@xixixao, thanks for the update. I'm open to moving the Kinde Auth integration to a separate NPM package as suggested. Please share any specific guidelines for this. I'll keep testing and refining the implementation in the meantime and await further instructions.

**Comment by umuthopeyildirim** [comment]
Hey @xixixao! Did Convex team decided on a action plan for this PR? In the meanwhile I think we should merge this PR for Kinde and Convex users.

**Comment by xixixao** [comment]
Hey @umuthopeyildirim, I think we're gonna go with a separate package. We'll use this PR as the basis. We can also point anyone interested in Kinde to this PR for vendoring into their codebase before that package is ready. Thanks again!

**Comment by oliwolff1** [comment]
Hey @xixixao,
Did you end up creating a separate package for the Kinde Auth integration with Convex.
By the way, I am from the Kinde team.

**Comment by xixixao** [comment]
Hey @oliwolff1, we haven't had the bandwidth to work on this yet.

**Comment by oliwolff1** [comment]
Hey @xixixao,
No worries at all.
Please reach out when you do, we would love to share more broadly this Kinde x Convex integration.

**Comment by umuthopeyildirim** [comment]
Apologies for the delay, @xixixao and @oliwolff1!

The job hunt and research have kept me occupied, causing me to overlook this task in my to-do list. I hope this submission suffices! I'll can transfer them to `get-convex`.

Here are the GitHub repositories:
- [convex-kinde-auth](https://github.com/umuthopeyildirim/convex-kinde-auth)
- [react-kinde-convex](https://github.com/umuthopeyildirim/react-kinde-convex)

Thank you for your understanding!

**Pull request closed without merging**
